#!/usr/bin/env python3
import json

spells = {
    "archmage_blaze_storm": "Archmage's Blaze Storm",
    "archmage_burning_dash": "Archmage's Burning Dash",
    "archmage_fire_arrow": "Archmage's Fire Arrow",
    "archmage_fire_breath": "Archmage's Fire Breath",
    "archmage_fireball": "Archmage's Fireball",
    "archmage_firebolt": "Archmage's Firebolt",
    "archmage_flaming_barrage": "Archmage's Flaming Barrage",
    "archmage_flaming_strike": "Archmage's Flaming Strike",
    "archmage_heat_surge": "Archmage's Heat Surge",
    "archmage_magma_bomb": "Archmage's Magma Bomb",
    "archmage_raise_hell": "Archmage's Raise Hell",
    "archmage_scorch": "Archmage's Scorch",
    "archmage_wall_of_fire": "Archmage's Wall of Fire",
    "archmage_cone_of_cold": "Archmage's Cone of Cold",
    "archmage_frost_step": "Archmage's Frost Step",
    "archmage_frostbite": "Archmage's Frostbite",
    "archmage_frostwave": "Archmage's Frostwave",
    "archmage_ice_block": "Archmage's Ice Block",
    "archmage_ice_spikes": "Archmage's Ice Spikes",
    "archmage_ice_tomb": "Archmage's Ice Tomb",
    "archmage_icicle": "Archmage's Icicle",
    "archmage_ray_of_frost": "Archmage's Ray of Frost",
    "archmage_snowball": "Archmage's Snowball",
    "archmage_summon_polar_bear": "Archmage's Summon Polar Bear",
    "archmage_ascension": "Archmage's Ascension",
    "archmage_ball_lightning": "Archmage's Ball Lightning",
    "archmage_chain_lightning": "Archmage's Chain Lightning",
    "archmage_charge": "Archmage's Charge",
    "archmage_electrocute": "Archmage's Electrocute",
    "archmage_lightning_bolt": "Archmage's Lightning Bolt",
    "archmage_lightning_lance": "Archmage's Lightning Lance",
    "archmage_shockwave": "Archmage's Shockwave",
    "archmage_thunderstep": "Archmage's Thunderstep",
    "archmage_thunderstorm": "Archmage's Thunderstorm",
    "archmage_volt_strike": "Archmage's Volt Strike",
    "archmage_angel_wings": "Archmage's Angel Wings",
    "archmage_blessing_of_life": "Archmage's Blessing of Life",
    "archmage_cleanse": "Archmage's Cleanse",
    "archmage_cloud_of_regeneration": "Archmage's Cloud of Regeneration",
    "archmage_divine_smite": "Archmage's Divine Smite",
    "archmage_fortify": "Archmage's Fortify",
    "archmage_greater_heal": "Archmage's Greater Heal",
    "archmage_guiding_bolt": "Archmage's Guiding Bolt",
    "archmage_haste": "Archmage's Haste",
    "archmage_heal": "Archmage's Heal",
    "archmage_healing_circle": "Archmage's Healing Circle",
    "archmage_sunbeam": "Archmage's Sunbeam",
    "archmage_wisp": "Archmage's Wisp",
    "archmage_black_hole": "Archmage's Black Hole",
    "archmage_counterspell": "Archmage's Counterspell",
    "archmage_dragon_breath": "Archmage's Dragon Breath",
    "archmage_echoing_strikes": "Archmage's Echoing Strikes",
    "archmage_evasion": "Archmage's Evasion",
    "archmage_magic_arrow": "Archmage's Magic Arrow",
    "archmage_magic_missile": "Archmage's Magic Missile",
    "archmage_portal": "Archmage's Portal",
    "archmage_recall": "Archmage's Recall",
    "archmage_starfall": "Archmage's Starfall",
    "archmage_summon_ender_chest": "Archmage's Summon Ender Chest",
    "archmage_summon_swords": "Archmage's Summon Swords",
    "archmage_teleport": "Archmage's Teleport",
    "archmage_arrow_volley": "Archmage's Arrow Volley",
    "archmage_chain_creeper": "Archmage's Chain Creeper",
    "archmage_fang_strike": "Archmage's Fang Strike",
    "archmage_fang_ward": "Archmage's Fang Ward",
    "archmage_firecracker": "Archmage's Firecracker",
    "archmage_gust": "Archmage's Gust",
    "archmage_invisibility": "Archmage's Invisibility",
    "archmage_lob_creeper": "Archmage's Lob Creeper",
    "archmage_shield": "Archmage's Shield",
    "archmage_slow": "Archmage's Slow",
    "archmage_spectral_hammer": "Archmage's Spectral Hammer",
    "archmage_summon_horse": "Archmage's Summon Horse",
    "archmage_summon_vex": "Archmage's Summon Vex",
    "archmage_wololo": "Archmage's Wololo",
    "archmage_acupuncture": "Archmage's Acupuncture",
    "archmage_blood_needles": "Archmage's Blood Needles",
    "archmage_blood_slash": "Archmage's Blood Slash",
    "archmage_blood_step": "Archmage's Blood Step",
    "archmage_devour": "Archmage's Devour",
    "archmage_heartstop": "Archmage's Heartstop",
    "archmage_raise_dead": "Archmage's Raise Dead",
    "archmage_ray_of_siphoning": "Archmage's Ray of Siphoning",
    "archmage_sacrifice": "Archmage's Sacrifice",
    "archmage_wither_skull": "Archmage's Wither Skull",
    "archmage_acid_orb": "Archmage's Acid Orb",
    "archmage_blight": "Archmage's Blight",
    "archmage_earthquake": "Archmage's Earthquake",
    "archmage_firefly_swarm": "Archmage's Firefly Swarm",
    "archmage_gluttony": "Archmage's Gluttony",
    "archmage_oakskin": "Archmage's Oakskin",
    "archmage_poison_arrow": "Archmage's Poison Arrow",
    "archmage_poison_breath": "Archmage's Poison Breath",
    "archmage_poison_splash": "Archmage's Poison Splash",
    "archmage_root": "Archmage's Root",
    "archmage_spider_aspect": "Archmage's Spider Aspect",
    "archmage_stomp": "Archmage's Stomp",
    "archmage_touch_dig": "Archmage's Touch Dig",
    "archmage_abyssal_shroud": "Archmage's Abyssal Shroud",
    "archmage_eldritch_blast": "Archmage's Eldritch Blast",
    "archmage_planar_sight": "Archmage's Planar Sight",
    "archmage_pocket_dimension": "Archmage's Pocket Dimension",
    "archmage_sculk_tentacles": "Archmage's Sculk Tentacles",
    "archmage_sonic_boom": "Archmage's Sonic Boom",
    "archmage_telekinesis": "Archmage's Telekinesis",
}

# Read existing lang file
with open("src/main/resources/assets/moostack/lang/en_us.json", "r") as f:
    lang_data = json.load(f)

# Add spell translations
for spell_id, spell_name in spells.items():
    lang_data[f"spell.moostack.{spell_id}"] = spell_name

# Write updated lang file
with open("src/main/resources/assets/moostack/lang/en_us.json", "w") as f:
    json.dump(lang_data, f, indent=2)

print(f"Added {len(spells)} spell translations to en_us.json")