// Epic Fight Preference Items for Epic Knights Mods
// This file documents all armor and weapon items that need Epic Fight preferences
// Use these lists when configuring epicfight-client.toml

// =====================================================
// MINING PREFERRED ITEMS (armors - should stay in mining mode)
// =====================================================

const MINING_PREFERRED_ITEMS = [
    // === MAGISTUARMORY (Main Epic Knights) ===
    "magistuarmory:armet", "magistuarmory:knight_chestplate", "magistuarmory:knight_leggings", "magistuarmory:knight_boots",
    "magistuarmory:stechhelm", "magistuarmory:jousting_chestplate", "magistuarmory:jousting_leggings", "magistuarmory:jousting_boots",
    "magistuarmory:sallet", "magistuarmory:gothic_chestplate", "magistuarmory:gothic_leggings", "magistuarmory:gothic_boots",
    "magistuarmory:maximilian_helmet", "magistuarmory:maximilian_chestplate", "magistuarmory:maximilian_leggings", "magistuarmory:maximilian_boots",
    "magistuarmory:chainmail_helmet", "magistuarmory:chainmail_chestplate", "magistuarmory:chainmail_leggings", "magistuarmory:chainmail_boots",
    "magistuarmory:kettlehat", "magistuarmory:platemail_chestplate", "magistuarmory:platemail_leggings", "magistuarmory:platemail_boots",
    "magistuarmory:barbute", "magistuarmory:halfarmor_chestplate",
    "magistuarmory:greathelm", "magistuarmory:crusader_chestplate", "magistuarmory:crusader_leggings", "magistuarmory:crusader_boots",
    "magistuarmory:ceremonialarmet", "magistuarmory:ceremonial_chestplate", "magistuarmory:ceremonial_boots",
    "magistuarmory:coif", "magistuarmory:gambeson_chestplate", "magistuarmory:pantyhose", "magistuarmory:gambeson_boots",
    "magistuarmory:brigandine_chestplate", "magistuarmory:norman_helmet", "magistuarmory:shishak",
    "magistuarmory:rustedbarbute", "magistuarmory:rustedhalfarmor_chestplate",
    "magistuarmory:rustedgreathelm", "magistuarmory:rustedcrusader_chestplate", "magistuarmory:rustedcrusader_boots",
    "magistuarmory:rustednorman_helmet",
    "magistuarmory:rustedchainmail_helmet", "magistuarmory:rustedchainmail_chestplate", "magistuarmory:rustedchainmail_leggings", "magistuarmory:rustedchainmail_boots",
    "magistuarmory:rustedkettlehat",
    "magistuarmory:bascinet", "magistuarmory:xivcenturyknight_chestplate", "magistuarmory:xivcenturyknight_leggings", "magistuarmory:xivcenturyknight_boots",
    "magistuarmory:wingedhussar_chestplate",
    "magistuarmory:cuirassier_helmet", "magistuarmory:cuirassier_chestplate", "magistuarmory:cuirassier_leggings", "magistuarmory:cuirassier_boots",
    "magistuarmory:grand_bascinet", "magistuarmory:kastenbrust_chestplate", "magistuarmory:kastenbrust_leggings", "magistuarmory:kastenbrust_boots",
    "magistuarmory:face_helmet", "magistuarmory:lamellar_chestplate", "magistuarmory:lamellar_boots",

    // === MAGISTUARMORYADDON (Epic Knights Addon) ===
    "magistuarmoryaddon:dark_knight_helmet", "magistuarmoryaddon:dark_knight_chestplate", "magistuarmoryaddon:dark_knight_leggings", "magistuarmoryaddon:dark_knight_boots",
    "magistuarmoryaddon:dark_jousting_helmet", "magistuarmoryaddon:dark_jousting_chestplate", "magistuarmoryaddon:dark_jousting_leggings", "magistuarmoryaddon:dark_jousting_boots",
    "magistuarmoryaddon:dark_gothic_helmet", "magistuarmoryaddon:dark_gothic_chestplate", "magistuarmoryaddon:dark_gothic_leggings", "magistuarmoryaddon:dark_gothic_boots",
    "magistuarmoryaddon:dark_maximilian_helmet", "magistuarmoryaddon:dark_maximilian_chestplate", "magistuarmoryaddon:dark_maximilian_leggings", "magistuarmoryaddon:dark_maximilian_boots",
    "magistuarmoryaddon:dark_crusader_helmet", "magistuarmoryaddon:dark_crusader_chestplate", "magistuarmoryaddon:dark_crusader_leggings", "magistuarmoryaddon:dark_crusader_boots",
    "magistuarmoryaddon:dark_grand_bascinet", "magistuarmoryaddon:dark_kastenbrust_chestplate", "magistuarmoryaddon:dark_kastenbrust_leggings", "magistuarmoryaddon:dark_kastenbrust_boots",
    "magistuarmoryaddon:savoyard_helmet", "magistuarmoryaddon:morion",
    "magistuarmoryaddon:pikeman_chestplate", "magistuarmoryaddon:pikeman_boots",
    "magistuarmoryaddon:milanese_armet", "magistuarmoryaddon:british_armet",
    "magistuarmoryaddon:avant_chestplate", "magistuarmoryaddon:avant_leggings", "magistuarmoryaddon:avant_boots",
    "magistuarmoryaddon:visored_kettlehat", "magistuarmoryaddon:cervelliere", "magistuarmoryaddon:closed_barbute", "magistuarmoryaddon:bicoque",
    "magistuarmoryaddon:linen_coif", "magistuarmoryaddon:sallet_without_neck_protection", "magistuarmoryaddon:bellows_maximilian_helmet",
    "magistuarmoryaddon:kulah_khud", "magistuarmoryaddon:cuman_captain_helmet",
    "magistuarmoryaddon:mirror_chestplate", "magistuarmoryaddon:mirror_boots",
    "magistuarmoryaddon:saracen_helmet", "magistuarmoryaddon:saracen_chestplate", "magistuarmoryaddon:saracen_boots",
    "magistuarmoryaddon:early_greathelm", "magistuarmoryaddon:xiii_century_knight_chestplate", "magistuarmoryaddon:xiii_century_knight_leggings", "magistuarmoryaddon:xiii_century_knight_boots",
    "magistuarmoryaddon:klappvisor_bascinet", "magistuarmoryaddon:late_bascinet", "magistuarmoryaddon:lobster_tailed_helmet",
    "magistuarmoryaddon:chapel", "magistuarmoryaddon:chained_gambeson", "magistuarmoryaddon:chained_gambeson_boots",
    "magistuarmoryaddon:tablet_helmet", "magistuarmoryaddon:late_greathelm", "magistuarmoryaddon:burgundian_kettlehat",
    "magistuarmoryaddon:closed_burgonet", "magistuarmoryaddon:heavy_cuirassier_chestplate", "magistuarmoryaddon:heavy_cuirassier_boots",
    "magistuarmoryaddon:dark_heavy_cuirassier_chestplate", "magistuarmoryaddon:dark_heavy_cuirassier_boots",
    "magistuarmoryaddon:light_burgonet", "magistuarmoryaddon:late_burgonet",
    "magistuarmoryaddon:devilish_grotesque_maximilian_helmet", "magistuarmoryaddon:facial_grotesque_maximilian_helmet",
    "magistuarmoryaddon:dark_gilded_greenwich_armet", "magistuarmoryaddon:dark_gilded_greenwich_chestplate", "magistuarmoryaddon:dark_gilded_greenwich_boots",
    "magistuarmoryaddon:dark_greenwich_armet", "magistuarmoryaddon:dark_greenwich_chestplate", "magistuarmoryaddon:dark_greenwich_boots",
    "magistuarmoryaddon:late_sallet", "magistuarmoryaddon:dark_late_sallet",
    "magistuarmoryaddon:steel_puff_and_slash_chestplate", "magistuarmoryaddon:steel_puff_and_slash_boots",
    "magistuarmoryaddon:gilded_steel_puff_and_slash_chestplate", "magistuarmoryaddon:gilded_steel_puff_and_slash_boots",
    "magistuarmoryaddon:sturmhaube", "magistuarmoryaddon:silvered_dark_bellows_maximilian_helmet",
    "magistuarmoryaddon:silvered_dark_maximilian_helmet", "magistuarmoryaddon:silvered_dark_maximilian_chestplate", "magistuarmoryaddon:silvered_dark_maximilian_boots",
    "magistuarmoryaddon:gilded_grand_bascinet", "magistuarmoryaddon:ceremonial_kastenbrust_chestplate", "magistuarmoryaddon:ceremonial_kastenbrust_boots",
    "magistuarmoryaddon:gilded_xivcenturyknight_chestplate", "magistuarmoryaddon:gilded_xivcenturyknight_boots",
    "magistuarmoryaddon:gallowglass_chestplate", "magistuarmoryaddon:gallowglass_leggings", "magistuarmoryaddon:gallowglass_boots",
    "magistuarmoryaddon:english_knight_chestplate", "magistuarmoryaddon:english_knight_boots",
    "magistuarmoryaddon:gilded_half_armor", "magistuarmoryaddon:gilded_exquisite_maximilian_helmet",
    "magistuarmoryaddon:gilded_maximilian_helmet", "magistuarmoryaddon:gilded_maximilian_chestplate", "magistuarmoryaddon:gilded_maximilian_boots",
    "magistuarmoryaddon:coat_of_plates_chestplate", "magistuarmoryaddon:coat_of_plates_boots",
    "magistuarmoryaddon:silvered_dark_half_armor", "magistuarmoryaddon:gilded_dark_sallet",
    "magistuarmoryaddon:gilded_dark_gothic_chestplate", "magistuarmoryaddon:gilded_dark_gothic_boots",
    "magistuarmoryaddon:gilded_sallet", "magistuarmoryaddon:gilded_gothic_chestplate", "magistuarmoryaddon:gilded_gothic_boots",
    "magistuarmoryaddon:gilded_greenwich_armet", "magistuarmoryaddon:gilded_greenwich_chestplate", "magistuarmoryaddon:gilded_greenwich_boots",
    "magistuarmoryaddon:greenwich_armet", "magistuarmoryaddon:greenwich_chestplate", "magistuarmoryaddon:greenwich_boots",
    // Puff and slash color variants
    "magistuarmoryaddon:orange_puff_and_slash_chestplate", "magistuarmoryaddon:orange_puff_and_slash_leggings",
    "magistuarmoryaddon:magenta_puff_and_slash_chestplate", "magistuarmoryaddon:magenta_puff_and_slash_leggings",
    "magistuarmoryaddon:light_blue_puff_and_slash_chestplate", "magistuarmoryaddon:light_blue_puff_and_slash_leggings",
    "magistuarmoryaddon:yellow_puff_and_slash_chestplate", "magistuarmoryaddon:yellow_puff_and_slash_leggings",
    "magistuarmoryaddon:lime_puff_and_slash_chestplate", "magistuarmoryaddon:lime_puff_and_slash_leggings",
    "magistuarmoryaddon:pink_puff_and_slash_chestplate", "magistuarmoryaddon:pink_puff_and_slash_leggings",
    "magistuarmoryaddon:gray_puff_and_slash_chestplate", "magistuarmoryaddon:gray_puff_and_slash_leggings",
    "magistuarmoryaddon:light_gray_puff_and_slash_chestplate", "magistuarmoryaddon:light_gray_puff_and_slash_leggings",
    "magistuarmoryaddon:cyan_puff_and_slash_chestplate", "magistuarmoryaddon:cyan_puff_and_slash_leggings",
    "magistuarmoryaddon:purple_puff_and_slash_chestplate", "magistuarmoryaddon:purple_puff_and_slash_leggings",
    "magistuarmoryaddon:blue_puff_and_slash_chestplate", "magistuarmoryaddon:blue_puff_and_slash_leggings",
    "magistuarmoryaddon:brown_puff_and_slash_chestplate", "magistuarmoryaddon:brown_puff_and_slash_leggings",
    "magistuarmoryaddon:green_puff_and_slash_chestplate", "magistuarmoryaddon:green_puff_and_slash_leggings",
    "magistuarmoryaddon:red_puff_and_slash_chestplate", "magistuarmoryaddon:red_puff_and_slash_leggings",
    "magistuarmoryaddon:black_puff_and_slash_chestplate", "magistuarmoryaddon:black_puff_and_slash_leggings",
    "magistuarmoryaddon:white_puff_and_slash_chestplate", "magistuarmoryaddon:white_puff_and_slash_leggings",
    "magistuarmoryaddon:puff_and_slash_boots",
    "magistuarmoryaddon:scale_helmet", "magistuarmoryaddon:condottiero_cap", "magistuarmoryaddon:sugarloaf_helmet", "magistuarmoryaddon:gilded_sugarloaf_helmet",
    "magistuarmoryaddon:patrician_tuher_helmet", "magistuarmoryaddon:late_kettlehat", "magistuarmoryaddon:close_helmet",
    "magistuarmoryaddon:exquisite_maximilian_helmet", "magistuarmoryaddon:proto_maximilian_chestplate", "magistuarmoryaddon:proto_maximilian_boots",
    "magistuarmoryaddon:dark_proto_maximilian_chestplate", "magistuarmoryaddon:dark_proto_maximilian_boots",
    "magistuarmoryaddon:heavy_brigandine_chestplate", "magistuarmoryaddon:heavy_brigandine_leggings", "magistuarmoryaddon:heavy_brigandine_boots",
    "magistuarmoryaddon:gilded_heavy_brigandine_chestplate", "magistuarmoryaddon:gilded_heavy_brigandine_leggings", "magistuarmoryaddon:gilded_heavy_brigandine_boots",
    "magistuarmoryaddon:dark_heavy_brigandine_chestplate", "magistuarmoryaddon:dark_heavy_brigandine_leggings", "magistuarmoryaddon:dark_heavy_brigandine_boots",
    "magistuarmoryaddon:cabasset", "magistuarmoryaddon:gilded_cabasset", "magistuarmoryaddon:early_cabasset",
    "magistuarmoryaddon:dark_early_cabasset", "magistuarmoryaddon:gilded_early_cabasset",
    "magistuarmoryaddon:straw_hat", "magistuarmoryaddon:fancy_hat", "magistuarmoryaddon:tunic", "magistuarmoryaddon:tunic_boots",
    "magistuarmoryaddon:embosed_parade_burgonet", "magistuarmoryaddon:embosed_parade_chestplate", "magistuarmoryaddon:embosed_parade_boots",
    "magistuarmoryaddon:dark_gilded_parade_burgonet", "magistuarmoryaddon:dark_gilded_parade_chestplate", "magistuarmoryaddon:dark_gilded_parade_boots",
    "magistuarmoryaddon:doublet", "magistuarmoryaddon:shoes", "magistuarmoryaddon:articulated_chestplate", "magistuarmoryaddon:cuman_helmet",
    // Darkblued variants
    "magistuarmoryaddon:darkblued_gothic_chestplate", "magistuarmoryaddon:darkblued_gothic_leggings", "magistuarmoryaddon:darkblued_gothic_boots",
    "magistuarmoryaddon:darkblued_greenwich_armet", "magistuarmoryaddon:darkblued_greenwich_chestplate", "magistuarmoryaddon:darkblued_greenwich_boots",
    "magistuarmoryaddon:darkblued_kastenbrust_chestplate", "magistuarmoryaddon:darkblued_kastenbrust_leggings", "magistuarmoryaddon:darkblued_kastenbrust_boots",
    "magistuarmoryaddon:darkblued_armet", "magistuarmoryaddon:darkblued_knight_chestplate", "magistuarmoryaddon:darkblued_knight_leggings", "magistuarmoryaddon:darkblued_knight_boots",
    "magistuarmoryaddon:darkblued_maximilian_helmet", "magistuarmoryaddon:darkblued_maximilian_chestplate", "magistuarmoryaddon:darkblued_maximilian_leggings", "magistuarmoryaddon:darkblued_maximilian_boots",
    "magistuarmoryaddon:darkblued_sallet",
    "magistuarmoryaddon:engraved_close_helmet", "magistuarmoryaddon:engraved_chestplate",
    "magistuarmoryaddon:fox_grotesque_maximilian_helmet",
    // Fully gilded variants
    "magistuarmoryaddon:fully_gilded_armet", "magistuarmoryaddon:fully_gilded_articulated_chestplate",
    "magistuarmoryaddon:fully_gilded_gothic_chestplate", "magistuarmoryaddon:fully_gilded_gothic_leggings", "magistuarmoryaddon:fully_gilded_gothic_boots",
    "magistuarmoryaddon:fully_gilded_grand_bascinet",
    "magistuarmoryaddon:fully_gilded_greenwich_armet", "magistuarmoryaddon:fully_gilded_greenwich_chestplate", "magistuarmoryaddon:fully_gilded_greenwich_boots",
    "magistuarmoryaddon:fully_gilded_grilled_helmet",
    "magistuarmoryaddon:fully_gilded_jousting_helmet", "magistuarmoryaddon:fully_gilded_jousting_chestplate", "magistuarmoryaddon:fully_gilded_jousting_leggings", "magistuarmoryaddon:fully_gilded_jousting_boots",
    "magistuarmoryaddon:fully_gilded_kastenbrust_chestplate", "magistuarmoryaddon:fully_gilded_kastenbrust_leggings", "magistuarmoryaddon:fully_gilded_kastenbrust_boots",
    "magistuarmoryaddon:fully_gilded_knight_chestplate", "magistuarmoryaddon:fully_gilded_knight_leggings", "magistuarmoryaddon:fully_gilded_knight_boots",
    "magistuarmoryaddon:fully_gilded_maximilian_helmet", "magistuarmoryaddon:fully_gilded_maximilian_chestplate", "magistuarmoryaddon:fully_gilded_maximilian_leggings", "magistuarmoryaddon:fully_gilded_maximilian_boots",
    "magistuarmoryaddon:fully_gilded_milanese_armet", "magistuarmoryaddon:fully_gilded_sallet",
    "magistuarmoryaddon:gilded_chainmail_coif", "magistuarmoryaddon:gilded_chainmail_chestplate", "magistuarmoryaddon:gilded_chainmail_leggings",
    "magistuarmoryaddon:gilded_close_helmet",
    "magistuarmoryaddon:gilded_darkblued_greenwich_armet", "magistuarmoryaddon:gilded_darkblued_greenwich_chestplate", "magistuarmoryaddon:gilded_darkblued_greenwich_boots",
    "magistuarmoryaddon:gilded_dark_close_helmet", "magistuarmoryaddon:gilded_fox_grotesque_maximilian_helmet", "magistuarmoryaddon:gilded_grilled_helmet",
    "magistuarmoryaddon:grilled_helmet", "magistuarmoryaddon:lion_helmet", "magistuarmoryaddon:mamluk_helmet", "magistuarmoryaddon:maximilian_burgonet",
    "magistuarmoryaddon:opened_sallet",
    "magistuarmoryaddon:splint_chestplate", "magistuarmoryaddon:splint_leggings", "magistuarmoryaddon:splint_boots",
    "magistuarmoryaddon:tilted_puff_and_slash_hat",
    "magistuarmoryaddon:alla_tedesca_chestplate", "magistuarmoryaddon:alla_tedesca_boots",
    "magistuarmoryaddon:peascod_chestplate", "magistuarmoryaddon:gilded_peascod_chestplate", "magistuarmoryaddon:dark_peascod_chestplate", "magistuarmoryaddon:gilded_dark_peascod_chestplate",
    "magistuarmoryaddon:two_eye_slits_sallet", "magistuarmoryaddon:sallet_without_visor", "magistuarmoryaddon:german_bascinet", "magistuarmoryaddon:light_cuman_helmet",

    // === ANTIQUELEGACY (Epic Knights Antique Legacy) ===
    "antiquelegacy:attic_helmet", "antiquelegacy:bell_cuirass", "antiquelegacy:beotian_helmet", "antiquelegacy:bronzed_gallea",
    "antiquelegacy:bronze_ridge_helmet", "antiquelegacy:bronze_coolus", "antiquelegacy:bronze_intercisa", "antiquelegacy:bronze_melos",
    "antiquelegacy:bronze_montefortino_helmet", "antiquelegacy:bronze_muscle_cuirass", "antiquelegacy:bronze_niederbieber_helmet",
    "antiquelegacy:bronze_phrygian_helmet", "antiquelegacy:bronze_pilos_closet", "antiquelegacy:bronze_pilos", "antiquelegacy:bronze_squamata",
    "antiquelegacy:roman_parade_helmet", "antiquelegacy:bronze_apulo_corinthian_helmet", "antiquelegacy:chalcidian_helmet", "antiquelegacy:corinthian_helmet",
    "antiquelegacy:gallea", "antiquelegacy:gilded_gallea", "antiquelegacy:golden_ridge_helmet", "antiquelegacy:greek_greaves",
    "antiquelegacy:hamata", "antiquelegacy:hamata_optio", "antiquelegacy:heddernheim_helmet", "antiquelegacy:illirian_helmet",
    "antiquelegacy:iron_ridge_helmet", "antiquelegacy:iron_intercisa", "antiquelegacy:iron_melos", "antiquelegacy:iron_niederbieber_helmet",
    "antiquelegacy:iron_pilos", "antiquelegacy:iron_squamata", "antiquelegacy:late_hamata", "antiquelegacy:murmillo_helmet",
    "antiquelegacy:musculata", "antiquelegacy:officer_squamata", "antiquelegacy:open_attic_helmet", "antiquelegacy:provocator_helmet",
    "antiquelegacy:secutor_helmet", "antiquelegacy:segmentata", "antiquelegacy:thracian_helmet", "antiquelegacy:tinned_muscle_cuirass",
    "antiquelegacy:tinned_phrygian_helmet", "antiquelegacy:weathered_corinthian_helmet", "antiquelegacy:cardiophylax", "antiquelegacy:linothorax",
    "antiquelegacy:iron_thorax", "antiquelegacy:scale_thorax", "antiquelegacy:sandals", "antiquelegacy:kuban_helmet",
    "antiquelegacy:scythian_scale_thorax", "antiquelegacy:scythian_attic_helmet", "antiquelegacy:iron_scythian_scale_helmet", "antiquelegacy:bronze_scythian_scale_helmet",
    "antiquelegacy:phrygian_cap", "antiquelegacy:short_phrygian_cap", "antiquelegacy:iron_roman_greaves", "antiquelegacy:bronze_roman_greaves",
    "antiquelegacy:agen_port_helmet", "antiquelegacy:celtic_montefortino_helmet", "antiquelegacy:la_gorge_meillet", "antiquelegacy:sava_helmet",
    "antiquelegacy:waterloo_helmet", "antiquelegacy:celtic_tunic", "antiquelegacy:celtic_tunic_boots", "antiquelegacy:celtic_pants",
    "antiquelegacy:red_celtic_pants", "antiquelegacy:green_celtic_pants", "antiquelegacy:brown_celtic_pants", "antiquelegacy:black_celtic_pants"
];

// =====================================================
// COMBAT PREFERRED ITEMS (weapons - should switch to combat mode)
// =====================================================

const COMBAT_PREFERRED_ITEMS = [
    // === MAGISTUARMORY (Main Epic Knights) - Material variants ===
    // Wood weapons
    "magistuarmory:wood_stylet", "magistuarmory:wood_shortsword", "magistuarmory:wood_katzbalger", "magistuarmory:wood_pike",
    "magistuarmory:wood_ranseur", "magistuarmory:wood_ahlspiess", "magistuarmory:wood_chivalrylance", "magistuarmory:wood_bastardsword",
    "magistuarmory:wood_estoc", "magistuarmory:wood_claymore", "magistuarmory:wood_zweihander", "magistuarmory:wood_flamebladedsword",
    "magistuarmory:wood_lochaberaxe", "magistuarmory:wood_concavehalberd", "magistuarmory:wood_heavymace", "magistuarmory:wood_heavywarhammer",
    "magistuarmory:wood_lucernhammer", "magistuarmory:wood_morgenstern", "magistuarmory:wood_chainmorgenstern", "magistuarmory:wood_guisarme",
    // Iron weapons
    "magistuarmory:iron_stylet", "magistuarmory:iron_shortsword", "magistuarmory:iron_katzbalger", "magistuarmory:iron_pike",
    "magistuarmory:iron_ranseur", "magistuarmory:iron_ahlspiess", "magistuarmory:iron_chivalrylance", "magistuarmory:iron_bastardsword",
    "magistuarmory:iron_estoc", "magistuarmory:iron_claymore", "magistuarmory:iron_zweihander", "magistuarmory:iron_flamebladedsword",
    "magistuarmory:iron_lochaberaxe", "magistuarmory:iron_concavehalberd", "magistuarmory:iron_heavymace", "magistuarmory:iron_heavywarhammer",
    "magistuarmory:iron_lucernhammer", "magistuarmory:iron_morgenstern", "magistuarmory:iron_chainmorgenstern", "magistuarmory:iron_guisarme",
    // Gold weapons
    "magistuarmory:gold_stylet", "magistuarmory:gold_shortsword", "magistuarmory:gold_katzbalger", "magistuarmory:gold_pike",
    "magistuarmory:gold_ranseur", "magistuarmory:gold_ahlspiess", "magistuarmory:gold_chivalrylance", "magistuarmory:gold_bastardsword",
    "magistuarmory:gold_estoc", "magistuarmory:gold_claymore", "magistuarmory:gold_zweihander", "magistuarmory:gold_flamebladedsword",
    "magistuarmory:gold_lochaberaxe", "magistuarmory:gold_concavehalberd", "magistuarmory:gold_heavymace", "magistuarmory:gold_heavywarhammer",
    "magistuarmory:gold_lucernhammer", "magistuarmory:gold_morgenstern", "magistuarmory:gold_chainmorgenstern", "magistuarmory:gold_guisarme",
    // Diamond weapons
    "magistuarmory:diamond_stylet", "magistuarmory:diamond_shortsword", "magistuarmory:diamond_katzbalger", "magistuarmory:diamond_pike",
    "magistuarmory:diamond_ranseur", "magistuarmory:diamond_ahlspiess", "magistuarmory:diamond_chivalrylance", "magistuarmory:diamond_bastardsword",
    "magistuarmory:diamond_estoc", "magistuarmory:diamond_claymore", "magistuarmory:diamond_zweihander", "magistuarmory:diamond_flamebladedsword",
    "magistuarmory:diamond_lochaberaxe", "magistuarmory:diamond_concavehalberd", "magistuarmory:diamond_heavymace", "magistuarmory:diamond_heavywarhammer",
    "magistuarmory:diamond_lucernhammer", "magistuarmory:diamond_morgenstern", "magistuarmory:diamond_chainmorgenstern", "magistuarmory:diamond_guisarme",
    // Netherite weapons
    "magistuarmory:netherite_stylet", "magistuarmory:netherite_shortsword", "magistuarmory:netherite_katzbalger", "magistuarmory:netherite_pike",
    "magistuarmory:netherite_ranseur", "magistuarmory:netherite_ahlspiess", "magistuarmory:netherite_chivalrylance", "magistuarmory:netherite_bastardsword",
    "magistuarmory:netherite_estoc", "magistuarmory:netherite_claymore", "magistuarmory:netherite_zweihander", "magistuarmory:netherite_flamebladedsword",
    "magistuarmory:netherite_lochaberaxe", "magistuarmory:netherite_concavehalberd", "magistuarmory:netherite_heavymace", "magistuarmory:netherite_heavywarhammer",
    "magistuarmory:netherite_lucernhammer", "magistuarmory:netherite_morgenstern", "magistuarmory:netherite_chainmorgenstern", "magistuarmory:netherite_guisarme",
    // Steel weapons
    "magistuarmory:steel_stylet", "magistuarmory:steel_shortsword", "magistuarmory:steel_katzbalger", "magistuarmory:steel_pike",
    "magistuarmory:steel_ranseur", "magistuarmory:steel_ahlspiess", "magistuarmory:steel_chivalrylance", "magistuarmory:steel_bastardsword",
    "magistuarmory:steel_estoc", "magistuarmory:steel_claymore", "magistuarmory:steel_zweihander", "magistuarmory:steel_flamebladedsword",
    "magistuarmory:steel_lochaberaxe", "magistuarmory:steel_concavehalberd", "magistuarmory:steel_heavymace", "magistuarmory:steel_heavywarhammer",
    "magistuarmory:steel_lucernhammer", "magistuarmory:steel_morgenstern", "magistuarmory:steel_chainmorgenstern", "magistuarmory:steel_guisarme",
    // Bronze weapons
    "magistuarmory:bronze_stylet", "magistuarmory:bronze_shortsword", "magistuarmory:bronze_katzbalger", "magistuarmory:bronze_pike",
    "magistuarmory:bronze_ranseur", "magistuarmory:bronze_ahlspiess", "magistuarmory:bronze_chivalrylance", "magistuarmory:bronze_bastardsword",
    "magistuarmory:bronze_estoc", "magistuarmory:bronze_claymore", "magistuarmory:bronze_zweihander", "magistuarmory:bronze_flamebladedsword",
    "magistuarmory:bronze_lochaberaxe", "magistuarmory:bronze_concavehalberd", "magistuarmory:bronze_heavymace", "magistuarmory:bronze_heavywarhammer",
    "magistuarmory:bronze_lucernhammer", "magistuarmory:bronze_morgenstern", "magistuarmory:bronze_chainmorgenstern", "magistuarmory:bronze_guisarme",
    // Unique weapons
    "magistuarmory:blacksmith_hammer", "magistuarmory:barbedclub", "magistuarmory:pitchfork", "magistuarmory:noble_sword",
    "magistuarmory:rusted_bastardsword", "magistuarmory:rusted_heavymace", "magistuarmory:club", "magistuarmory:messer_sword",
    "magistuarmory:longbow", "magistuarmory:heavy_crossbow",
    // Shields (treated as combat items)
    "magistuarmory:wood_heatershield", "magistuarmory:iron_heatershield", "magistuarmory:gold_heatershield", "magistuarmory:diamond_heatershield", "magistuarmory:netherite_heatershield", "magistuarmory:steel_heatershield", "magistuarmory:bronze_heatershield",
    "magistuarmory:wood_target", "magistuarmory:iron_target", "magistuarmory:gold_target", "magistuarmory:diamond_target", "magistuarmory:netherite_target", "magistuarmory:steel_target", "magistuarmory:bronze_target",
    "magistuarmory:wood_buckler", "magistuarmory:iron_buckler", "magistuarmory:gold_buckler", "magistuarmory:diamond_buckler", "magistuarmory:netherite_buckler", "magistuarmory:steel_buckler", "magistuarmory:bronze_buckler",
    "magistuarmory:wood_rondache", "magistuarmory:iron_rondache", "magistuarmory:gold_rondache", "magistuarmory:diamond_rondache", "magistuarmory:netherite_rondache", "magistuarmory:steel_rondache", "magistuarmory:bronze_rondache",
    "magistuarmory:wood_tartsche", "magistuarmory:iron_tartsche", "magistuarmory:gold_tartsche", "magistuarmory:diamond_tartsche", "magistuarmory:netherite_tartsche", "magistuarmory:steel_tartsche", "magistuarmory:bronze_tartsche",
    "magistuarmory:wood_ellipticalshield", "magistuarmory:iron_ellipticalshield", "magistuarmory:gold_ellipticalshield", "magistuarmory:diamond_ellipticalshield", "magistuarmory:netherite_ellipticalshield", "magistuarmory:steel_ellipticalshield", "magistuarmory:bronze_ellipticalshield",
    "magistuarmory:wood_roundshield", "magistuarmory:iron_roundshield", "magistuarmory:gold_roundshield", "magistuarmory:diamond_roundshield", "magistuarmory:netherite_roundshield", "magistuarmory:steel_roundshield", "magistuarmory:bronze_roundshield",
    "magistuarmory:wood_pavese", "magistuarmory:iron_pavese", "magistuarmory:gold_pavese", "magistuarmory:diamond_pavese", "magistuarmory:netherite_pavese", "magistuarmory:steel_pavese", "magistuarmory:bronze_pavese",
    "magistuarmory:wood_kiteshield", "magistuarmory:iron_kiteshield", "magistuarmory:gold_kiteshield", "magistuarmory:diamond_kiteshield", "magistuarmory:netherite_kiteshield", "magistuarmory:steel_kiteshield", "magistuarmory:bronze_kiteshield",
    "magistuarmory:corruptedroundshield",

    // === MAGISTUARMORYADDON (Epic Knights Addon) ===
    "magistuarmoryaddon:steel_dueling_shield", "magistuarmoryaddon:steel_bar_mace", "magistuarmoryaddon:steel_battleaxe", "magistuarmoryaddon:steel_crow_beak",
    "magistuarmoryaddon:steel_francisca_axe", "magistuarmoryaddon:steel_round_mace", "magistuarmoryaddon:steel_war_axe", "magistuarmoryaddon:steel_war_hammer",
    "magistuarmoryaddon:steel_bollock_dagger", "magistuarmoryaddon:steel_dagger", "magistuarmoryaddon:steel_parrying_dagger", "magistuarmoryaddon:steel_rondel_dagger",
    "magistuarmoryaddon:steel_sickle", "magistuarmoryaddon:steel_executioners_sword", "magistuarmoryaddon:steel_german_greatsword", "magistuarmoryaddon:steel_two_handed_messer",
    "magistuarmoryaddon:steel_english_poleaxe", "magistuarmoryaddon:steel_french_halberd", "magistuarmoryaddon:steel_italian_poleaxe", "magistuarmoryaddon:steel_swiss_halberd",
    "magistuarmoryaddon:steel_lance", "magistuarmoryaddon:steel_broadaxe", "magistuarmoryaddon:steel_daneaxe", "magistuarmoryaddon:steel_gallowglass_axe",
    "magistuarmoryaddon:steel_hammer_spear", "magistuarmoryaddon:steel_two_handed_evening_star",
    "magistuarmoryaddon:steel_cavalry_sabre", "magistuarmoryaddon:steel_cutlass", "magistuarmoryaddon:steel_falchion", "magistuarmoryaddon:steel_feder",
    "magistuarmoryaddon:steel_grand_falchion", "magistuarmoryaddon:steel_king_sword", "magistuarmoryaddon:steel_longsword", "magistuarmoryaddon:steel_long_seax",
    "magistuarmoryaddon:steel_maciejowski_messer", "magistuarmoryaddon:steel_messer_sword", "magistuarmoryaddon:steel_rapier", "magistuarmoryaddon:steel_scimitar",
    "magistuarmoryaddon:steel_sidesword", "magistuarmoryaddon:training_sword",
    "magistuarmoryaddon:steel_billhook", "magistuarmoryaddon:steel_boar_spear", "magistuarmoryaddon:steel_fauchard", "magistuarmoryaddon:steel_glaive",
    "magistuarmoryaddon:steel_goedendag", "magistuarmoryaddon:steel_military_fork", "magistuarmoryaddon:steel_partisan", "magistuarmoryaddon:steel_scythe",
    "magistuarmoryaddon:steel_short_spear", "magistuarmoryaddon:steel_voulge", "magistuarmoryaddon:steel_welsh_guisarme",
    "magistuarmoryaddon:steel_arming_sword_type_xiii", "magistuarmoryaddon:steel_arming_sword_type_xiv", "magistuarmoryaddon:steel_arming_sword_type_xv",
    "magistuarmoryaddon:rich_saxon_sword", "magistuarmoryaddon:steel_sabre", "magistuarmoryaddon:steel_saxon_sword", "magistuarmoryaddon:steel_short_seax", "magistuarmoryaddon:steel_swordbreaker",

    // === ANTIQUELEGACY (Epic Knights Antique Legacy) ===
    "antiquelegacy:iron_antique_dagger", "antiquelegacy:iron_sica", "antiquelegacy:eagle_standard", "antiquelegacy:weathered_eagle_standard",
    "antiquelegacy:iron_antique_spear", "antiquelegacy:iron_doru", "antiquelegacy:iron_retiarius", "antiquelegacy:iron_sarissa", "antiquelegacy:iron_triarii_spear",
    "antiquelegacy:iron_antique_sword", "antiquelegacy:iron_celtic_sword", "antiquelegacy:iron_early_spatha", "antiquelegacy:iron_gladiator_sword",
    "antiquelegacy:iron_gladius", "antiquelegacy:iron_kopis", "antiquelegacy:iron_republic_gladius", "antiquelegacy:iron_rhomphaia",
    "antiquelegacy:iron_single_edged_sword", "antiquelegacy:iron_spatha", "antiquelegacy:iron_xiphos",
    // Shields
    "antiquelegacy:bronze_republic_scutum", "antiquelegacy:bronze_imperial_scutum", "antiquelegacy:bronze_tureos", "antiquelegacy:bronze_hoplon", "antiquelegacy:pelta"
];

// Export for use in other scripts if needed
if (typeof module !== 'undefined') {
    module.exports = { MINING_PREFERRED_ITEMS, COMBAT_PREFERRED_ITEMS };
}

console.log('[Epic Fight Preferences] Loaded ' + MINING_PREFERRED_ITEMS.length + ' mining items and ' + COMBAT_PREFERRED_ITEMS.length + ' combat items');
