package com.zhintze.moostack.spells;

import com.zhintze.moostack.mooStack;
import io.redspace.ironsspellbooks.api.registry.SpellRegistry;
import io.redspace.ironsspellbooks.api.spells.AbstractSpell;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import com.zhintze.moostack.spells.blood.ArchmageAcupunctureSpell;
import com.zhintze.moostack.spells.blood.ArchmageBloodNeedlesSpell;
import com.zhintze.moostack.spells.blood.ArchmageBloodSlashSpell;
import com.zhintze.moostack.spells.blood.ArchmageBloodStepSpell;
import com.zhintze.moostack.spells.blood.ArchmageDevourSpell;
import com.zhintze.moostack.spells.blood.ArchmageHeartstopSpell;
import com.zhintze.moostack.spells.blood.ArchmageRaiseDeadSpell;
import com.zhintze.moostack.spells.blood.ArchmageRayOfSiphoningSpell;
import com.zhintze.moostack.spells.blood.ArchmageSacrificeSpell;
import com.zhintze.moostack.spells.blood.ArchmageWitherSkullSpell;
import com.zhintze.moostack.spells.eldritch.ArchmageAbyssalShroudSpell;
import com.zhintze.moostack.spells.eldritch.ArchmageEldritchBlastSpell;
import com.zhintze.moostack.spells.eldritch.ArchmagePlanarSightSpell;
import com.zhintze.moostack.spells.eldritch.ArchmagePocketDimensionSpell;
import com.zhintze.moostack.spells.eldritch.ArchmageSculkTentaclesSpell;
import com.zhintze.moostack.spells.eldritch.ArchmageSonicBoomSpell;
import com.zhintze.moostack.spells.eldritch.ArchmageTelekinesisSpell;
import com.zhintze.moostack.spells.ender.ArchmageBlackHoleSpell;
import com.zhintze.moostack.spells.ender.ArchmageCounterspellSpell;
import com.zhintze.moostack.spells.ender.ArchmageDragonBreathSpell;
import com.zhintze.moostack.spells.ender.ArchmageEchoingStrikesSpell;
import com.zhintze.moostack.spells.ender.ArchmageEvasionSpell;
import com.zhintze.moostack.spells.ender.ArchmageMagicArrowSpell;
import com.zhintze.moostack.spells.ender.ArchmageMagicMissileSpell;
import com.zhintze.moostack.spells.ender.ArchmageStarfallSpell;
import com.zhintze.moostack.spells.ender.ArchmageSummonSwordsSpell;
import com.zhintze.moostack.spells.ender.ArchmageTeleportSpell;
import com.zhintze.moostack.spells.evocation.ArchmageArrowVolleySpell;
import com.zhintze.moostack.spells.evocation.ArchmageChainCreeperSpell;
import com.zhintze.moostack.spells.evocation.ArchmageFangStrikeSpell;
import com.zhintze.moostack.spells.evocation.ArchmageFangWardSpell;
import com.zhintze.moostack.spells.evocation.ArchmageFirecrackerSpell;
import com.zhintze.moostack.spells.evocation.ArchmageGustSpell;
import com.zhintze.moostack.spells.evocation.ArchmageInvisibilitySpell;
import com.zhintze.moostack.spells.evocation.ArchmageLobCreeperSpell;
import com.zhintze.moostack.spells.evocation.ArchmageShieldSpell;
import com.zhintze.moostack.spells.evocation.ArchmageSlowSpell;
import com.zhintze.moostack.spells.evocation.ArchmageSpectralHammerSpell;
import com.zhintze.moostack.spells.evocation.ArchmageSummonHorseSpell;
import com.zhintze.moostack.spells.evocation.ArchmageSummonVexSpell;
import com.zhintze.moostack.spells.evocation.ArchmageWololoSpell;
import com.zhintze.moostack.spells.fire.ArchmageBlazeStormSpell;
import com.zhintze.moostack.spells.fire.ArchmageBurningDashSpell;
import com.zhintze.moostack.spells.fire.ArchmageFireArrowSpell;
import com.zhintze.moostack.spells.fire.ArchmageFireBreathSpell;
import com.zhintze.moostack.spells.fire.ArchmageFireballSpell;
import com.zhintze.moostack.spells.fire.ArchmageFireboltSpell;
import com.zhintze.moostack.spells.fire.ArchmageFlamingBarrageSpell;
import com.zhintze.moostack.spells.fire.ArchmageFlamingStrikeSpell;
import com.zhintze.moostack.spells.fire.ArchmageHeatSurgeSpell;
import com.zhintze.moostack.spells.fire.ArchmageMagmaBombSpell;
import com.zhintze.moostack.spells.fire.ArchmageRaiseHellSpell;
import com.zhintze.moostack.spells.fire.ArchmageScorchSpell;
import com.zhintze.moostack.spells.fire.ArchmageWallOfFireSpell;
import com.zhintze.moostack.spells.holy.ArchmageAngelWingsSpell;
import com.zhintze.moostack.spells.holy.ArchmageBlessingOfLifeSpell;
import com.zhintze.moostack.spells.holy.ArchmageCleanseSpell;
import com.zhintze.moostack.spells.holy.ArchmageCloudOfRegenerationSpell;
import com.zhintze.moostack.spells.holy.ArchmageDivineSmiteSpell;
import com.zhintze.moostack.spells.holy.ArchmageFortifySpell;
import com.zhintze.moostack.spells.holy.ArchmageGreaterHealSpell;
import com.zhintze.moostack.spells.holy.ArchmageGuidingBoltSpell;
import com.zhintze.moostack.spells.holy.ArchmageHasteSpell;
import com.zhintze.moostack.spells.holy.ArchmageHealSpell;
import com.zhintze.moostack.spells.holy.ArchmageHealingCircleSpell;
import com.zhintze.moostack.spells.holy.ArchmageSunbeamSpell;
import com.zhintze.moostack.spells.holy.ArchmageWispSpell;
import com.zhintze.moostack.spells.ice.ArchmageConeOfColdSpell;
import com.zhintze.moostack.spells.ice.ArchmageFrostStepSpell;
import com.zhintze.moostack.spells.ice.ArchmageFrostbiteSpell;
import com.zhintze.moostack.spells.ice.ArchmageFrostwaveSpell;
import com.zhintze.moostack.spells.ice.ArchmageIceBlockSpell;
import com.zhintze.moostack.spells.ice.ArchmageIceSpikesSpell;
import com.zhintze.moostack.spells.ice.ArchmageIceTombSpell;
import com.zhintze.moostack.spells.ice.ArchmageIcicleSpell;
import com.zhintze.moostack.spells.ice.ArchmageRayOfFrostSpell;
import com.zhintze.moostack.spells.ice.ArchmageSnowballSpell;
import com.zhintze.moostack.spells.ice.ArchmageSummonPolarBearSpell;
import com.zhintze.moostack.spells.lightning.ArchmageAscensionSpell;
import com.zhintze.moostack.spells.lightning.ArchmageBallLightningSpell;
import com.zhintze.moostack.spells.lightning.ArchmageChainLightningSpell;
import com.zhintze.moostack.spells.lightning.ArchmageChargeSpell;
import com.zhintze.moostack.spells.lightning.ArchmageElectrocuteSpell;
import com.zhintze.moostack.spells.lightning.ArchmageLightningBoltSpell;
import com.zhintze.moostack.spells.lightning.ArchmageLightningLanceSpell;
import com.zhintze.moostack.spells.lightning.ArchmageShockwaveSpell;
import com.zhintze.moostack.spells.lightning.ArchmageThunderStepSpell;
import com.zhintze.moostack.spells.lightning.ArchmageThunderstormSpell;
import com.zhintze.moostack.spells.lightning.ArchmageVoltStrikeSpell;
import com.zhintze.moostack.spells.nature.ArchmageAcidOrbSpell;
import com.zhintze.moostack.spells.nature.ArchmageBlightSpell;
import com.zhintze.moostack.spells.nature.ArchmageEarthquakeSpell;
import com.zhintze.moostack.spells.nature.ArchmageFireflySwarmSpell;
import com.zhintze.moostack.spells.nature.ArchmageGluttonySpell;
import com.zhintze.moostack.spells.nature.ArchmageOakskinSpell;
import com.zhintze.moostack.spells.nature.ArchmagePoisonArrowSpell;
import com.zhintze.moostack.spells.nature.ArchmagePoisonBreathSpell;
import com.zhintze.moostack.spells.nature.ArchmagePoisonSplashSpell;
import com.zhintze.moostack.spells.nature.ArchmageRootSpell;
import com.zhintze.moostack.spells.nature.ArchmageSpiderAspectSpell;
import com.zhintze.moostack.spells.nature.ArchmageStompSpell;
import com.zhintze.moostack.spells.nature.ArchmageTouchDigSpell;

import java.util.function.Supplier;

public class MooStackSpellRegistry {
    public static final DeferredRegister<AbstractSpell> SPELLS =
        DeferredRegister.create(SpellRegistry.SPELL_REGISTRY_KEY, mooStack.MODID);

    public static void register(IEventBus eventBus) {
        SPELLS.register(eventBus);
    }

    private static <T extends AbstractSpell> Supplier<T> registerSpell(T spell) {
        return SPELLS.register(spell.getSpellName(), () -> spell);
    }

    // Archmage Spell Registrations
    public static final Supplier<AbstractSpell> ARCHMAGE_BLAZESTORM = registerSpell(new ArchmageBlazeStormSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BURNINGDASH = registerSpell(new ArchmageBurningDashSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIREARROW = registerSpell(new ArchmageFireArrowSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIREBREATH = registerSpell(new ArchmageFireBreathSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIREBALL = registerSpell(new ArchmageFireballSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIREBOLT = registerSpell(new ArchmageFireboltSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FLAMINGBARRAGE = registerSpell(new ArchmageFlamingBarrageSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FLAMINGSTRIKE = registerSpell(new ArchmageFlamingStrikeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_HEATSURGE = registerSpell(new ArchmageHeatSurgeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_MAGMABOMB = registerSpell(new ArchmageMagmaBombSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_RAISEHELL = registerSpell(new ArchmageRaiseHellSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SCORCH = registerSpell(new ArchmageScorchSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_WALLOFFIRE = registerSpell(new ArchmageWallOfFireSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CONEOFCOLD = registerSpell(new ArchmageConeOfColdSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FROSTSTEP = registerSpell(new ArchmageFrostStepSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FROSTBITE = registerSpell(new ArchmageFrostbiteSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FROSTWAVE = registerSpell(new ArchmageFrostwaveSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ICEBLOCK = registerSpell(new ArchmageIceBlockSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ICESPIKES = registerSpell(new ArchmageIceSpikesSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ICETOMB = registerSpell(new ArchmageIceTombSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ICICLE = registerSpell(new ArchmageIcicleSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_RAYOFFROST = registerSpell(new ArchmageRayOfFrostSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SNOWBALL = registerSpell(new ArchmageSnowballSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SUMMONPOLARBEAR = registerSpell(new ArchmageSummonPolarBearSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ASCENSION = registerSpell(new ArchmageAscensionSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BALLLIGHTNING = registerSpell(new ArchmageBallLightningSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CHAINLIGHTNING = registerSpell(new ArchmageChainLightningSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CHARGE = registerSpell(new ArchmageChargeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ELECTROCUTE = registerSpell(new ArchmageElectrocuteSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_LIGHTNINGBOLT = registerSpell(new ArchmageLightningBoltSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_LIGHTNINGLANCE = registerSpell(new ArchmageLightningLanceSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SHOCKWAVE = registerSpell(new ArchmageShockwaveSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_THUNDERSTEP = registerSpell(new ArchmageThunderStepSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_THUNDERSTORM = registerSpell(new ArchmageThunderstormSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_VOLTSTRIKE = registerSpell(new ArchmageVoltStrikeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ANGELWINGS = registerSpell(new ArchmageAngelWingsSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLESSINGOFLIFE = registerSpell(new ArchmageBlessingOfLifeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CLEANSE = registerSpell(new ArchmageCleanseSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CLOUDOFREGENERATION = registerSpell(new ArchmageCloudOfRegenerationSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_DIVINESMITE = registerSpell(new ArchmageDivineSmiteSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FORTIFY = registerSpell(new ArchmageFortifySpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_GREATERHEAL = registerSpell(new ArchmageGreaterHealSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_GUIDINGBOLT = registerSpell(new ArchmageGuidingBoltSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_HASTE = registerSpell(new ArchmageHasteSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_HEAL = registerSpell(new ArchmageHealSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_HEALINGCIRCLE = registerSpell(new ArchmageHealingCircleSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SUNBEAM = registerSpell(new ArchmageSunbeamSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_WISP = registerSpell(new ArchmageWispSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLACKHOLE = registerSpell(new ArchmageBlackHoleSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_COUNTERSPELL = registerSpell(new ArchmageCounterspellSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_DRAGONBREATH = registerSpell(new ArchmageDragonBreathSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ECHOINGSTRIKES = registerSpell(new ArchmageEchoingStrikesSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_EVASION = registerSpell(new ArchmageEvasionSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_MAGICARROW = registerSpell(new ArchmageMagicArrowSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_MAGICMISSILE = registerSpell(new ArchmageMagicMissileSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_STARFALL = registerSpell(new ArchmageStarfallSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SUMMONSWORDS = registerSpell(new ArchmageSummonSwordsSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_TELEPORT = registerSpell(new ArchmageTeleportSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ARROWVOLLEY = registerSpell(new ArchmageArrowVolleySpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_CHAINCREEPER = registerSpell(new ArchmageChainCreeperSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FANGSTRIKE = registerSpell(new ArchmageFangStrikeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FANGWARD = registerSpell(new ArchmageFangWardSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIRECRACKER = registerSpell(new ArchmageFirecrackerSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_GUST = registerSpell(new ArchmageGustSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_INVISIBILITY = registerSpell(new ArchmageInvisibilitySpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_LOBCREEPER = registerSpell(new ArchmageLobCreeperSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SHIELD = registerSpell(new ArchmageShieldSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SLOW = registerSpell(new ArchmageSlowSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SPECTRALHAMMER = registerSpell(new ArchmageSpectralHammerSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SUMMONHORSE = registerSpell(new ArchmageSummonHorseSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SUMMONVEX = registerSpell(new ArchmageSummonVexSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_WOLOLO = registerSpell(new ArchmageWololoSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ACUPUNCTURE = registerSpell(new ArchmageAcupunctureSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLOODNEEDLES = registerSpell(new ArchmageBloodNeedlesSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLOODSLASH = registerSpell(new ArchmageBloodSlashSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLOODSTEP = registerSpell(new ArchmageBloodStepSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_DEVOUR = registerSpell(new ArchmageDevourSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_HEARTSTOP = registerSpell(new ArchmageHeartstopSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_RAISEDEAD = registerSpell(new ArchmageRaiseDeadSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_RAYOFSIPHONING = registerSpell(new ArchmageRayOfSiphoningSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SACRIFICE = registerSpell(new ArchmageSacrificeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_WITHERSKULL = registerSpell(new ArchmageWitherSkullSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ACIDORB = registerSpell(new ArchmageAcidOrbSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_BLIGHT = registerSpell(new ArchmageBlightSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_EARTHQUAKE = registerSpell(new ArchmageEarthquakeSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_FIREFLYSWARM = registerSpell(new ArchmageFireflySwarmSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_GLUTTONY = registerSpell(new ArchmageGluttonySpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_OAKSKIN = registerSpell(new ArchmageOakskinSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_POISONARROW = registerSpell(new ArchmagePoisonArrowSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_POISONBREATH = registerSpell(new ArchmagePoisonBreathSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_POISONSPLASH = registerSpell(new ArchmagePoisonSplashSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ROOT = registerSpell(new ArchmageRootSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SPIDERASPECT = registerSpell(new ArchmageSpiderAspectSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_STOMP = registerSpell(new ArchmageStompSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_TOUCHDIG = registerSpell(new ArchmageTouchDigSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ABYSSALSHROUD = registerSpell(new ArchmageAbyssalShroudSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_ELDRITCHBLAST = registerSpell(new ArchmageEldritchBlastSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_PLANARSIGHT = registerSpell(new ArchmagePlanarSightSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_POCKETDIMENSION = registerSpell(new ArchmagePocketDimensionSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SCULKTENTACLES = registerSpell(new ArchmageSculkTentaclesSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_SONICBOOM = registerSpell(new ArchmageSonicBoomSpell());
    public static final Supplier<AbstractSpell> ARCHMAGE_TELEKINESIS = registerSpell(new ArchmageTelekinesisSpell());
}
